name: 'PMD Code Analyzer Action'
author: Bill Yan
description: 'This action allows to use PMD Source Code Analyzer from GitHub Actions'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'award'  
  color: 'red'
